name: Fetch and Save Football Stats

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  fetch_and_save_stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install pandas lxml openpyxl requests

      - name: Run Script
        run: |
          python FootballData.py
        working-directory: Snippets/Football_Data

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'probablyvivek'
          git config --global user.email 'viv.tiwari13@gmail.com'
          git add .
          git commit -m "Updated football stats" -a || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
