name: Fetch and Save Football Stats

on:
  push: # Triggers the workflow on push events for any branch. Remove or comment out after testing.
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC daily.

jobs:
  fetch_and_save_stats:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl requests

    - name: Run Script
      run: python FootballData.py

    - name: Commit and Push if there are Changes
      run: |
        git config --global user.name 'probablyvivek'
        git config --global user.email 'viv.tiwari13@gmail.com'
        git add -A
        git commit -m "Updated stats" -a || echo "No changes to commit"
        git push
