name: Fetch and Save Football Stats

on:
  push: # Triggers the workflow on push events for any branch. Remove or comment out after testing.
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC daily.

jobs:
  fetch_and_save_stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Ensure this is the latest version or the one you intend to use

      - name: Set up Python
        uses: actions/setup-python@v4 # Ensure this is the latest version or the one you intend to use
        with:
          python-version: '3.9'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt-dev

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl requests lxml

      - name: Create Directory
        run: mkdir -p Programming/Snippets

      - name: Run Script
        run: python FootballData.py

		- name: Commit and Push Changes
		run: |
		  git config --global user.name 'probablyvivek'
		  git config --global user.email 'viv.tiwari13@gmail.com'
		  git add Programming/Snippets/*
		  git commit -m "Updated stats" -a || echo "No changes to commit"
		  git push --set-upstream origin HEAD:main
		env:
		  GITHUB_TOKEN: ${{ secrets.SNIPPETS_AUTOMATE }